{
 "title": "GitHub ARC Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SystemNamespace",
    "label": "ARC System Namespace",
    "query": {
     "query": "label_values(gha_controller_running_listeners,namespace)"
    }
   },
   {
    "name": "Scaleset",
    "label": "Scale Set",
    "query": {
     "query": "label_values(gha_registered_runners,name)"
    }
   },
   {
    "name": "RunnerNamespace",
    "label": "Runner Namespace",
    "query": {
     "query": "label_values(gha_desired_runners,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Runner Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Startup Duration",
   "type": "heatmap",
   "description": "Heat map showing the typical time before a job starts and whether the number of jobs in that time bucket are increasing or decreasing.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(gha_job_startup_duration_seconds_bucket{pod=~\"$Scaleset.*\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "heatmap",
   "description": "Heat map showing the typical time to complete a job and whether the number of jobs in that time bucket are increasing or decreasing.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (increase(gha_job_execution_duration_seconds_bucket{pod=~\"$Scaleset.*\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Assigned Jobs",
   "type": "gauge",
   "description": "The number of jobs assigned to the scale set.  The threshold is triggered with the number of assigned jobs exceeds the number of desired runners. This indicates that not all jobs will have an available runner.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_assigned_jobs{pod=~\"$Scaleset.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(gha_desired_runners{pod=~\"$Scaleset.*\"}) + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Runners",
   "type": "gauge",
   "description": "Number of runners desired by the scale set",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_desired_runners{pod=~\"$Scaleset.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle Runners",
   "type": "gauge",
   "description": "Number of registered runners that do not have assigned jobs.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_idle_runners{pod=~\"$Scaleset.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Jobs",
   "type": "gauge",
   "description": "The number of workflow jobs currently executing",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (gha_running_jobs{pod=~\"$Scaleset.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Runners",
   "type": "gauge",
   "description": "The number of runners in a failed state. These runners are typically misconfigured and count against the scale set's maximum limit.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_failed_ephemeral_runners{name=\"$Scaleset\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "stat",
   "description": "The number of active scale set listeners",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_running_listeners{namespace=~\"$SystemNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Runners",
   "type": "gauge",
   "description": "Number of runner pods that are waiting to be created. When this number exceeds the number of pods Kubernetes reports as Waiting, it indicate cluster performance issues.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_controller_pending_ephemeral_runners{name=~\"$Scaleset\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting) != 0 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registered Runners",
   "type": "gauge",
   "description": "The number of runners registered for processing queued jobs",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(gha_registered_runners{pod=~\"$Scaleset.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Runners",
   "type": "gauge",
   "description": "Number of runner pods in a running state",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gha_controller_running_ephemeral_runners{name=~\"$Scaleset\", namespace=~\"$RunnerNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out of Memory",
   "type": "stat",
   "description": "The number of containers that are reporting that they were terminated by an out-of-memory condition (OOMK.iller)",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\",namespace=~\"$RunnerNamespace\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak Container Memory",
   "type": "gauge",
   "description": "The peak memory used by a container in a given scale set's namespace.",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"arc-systems\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container I/O",
   "type": "timeseries",
   "description": "The sum of the reads and writes occurring within the runner namespace.",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$RunnerNamespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=~\"$RunnerNamespace\"}[$__rate_interval])) > 0 or vector(0)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Container Pod Status",
   "type": "bargauge",
   "description": "The Kubernetes-reported pod status.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"arc-systems\"}) != 0 or vector(0)",
     "legendFormat": "Ready"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\"arc-systems\"}) != 0 or vector(0)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"arc-systems\", reason=\"Completed\"}) != 0 or vector(0)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated_reason{namespace=~\"arc-systems\", reason=\"Error\"}) != 0 or vector(0)",
     "legendFormat": "Error"
    },
    { "expr": "sum(gha_desired_runners)+1", "legendFormat": "__auto" }
   ]
  },
  { "title": "Controller Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Reconcile Time",
   "type": "timeseries",
   "description": "The average time required for a reconciliation request to be processed. This reflects the time required for the controller to process a single request to modify a Kubernetes resource.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{namespace=\"$SystemNamespace\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue Queue Duration",
   "type": "timeseries",
   "description": "The average time a queued reconciliation request spends waiting to be processed.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(workqueue_queue_duration_seconds_sum{namespace=\"$SystemNamespace\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation Errors",
   "type": "timeseries",
   "description": "Errors indicate that controller has not achieved a desired state and is requesting Kubernetes to queue another request for reconciliation. Ideally, this number remains close to zero. An increasing number can indicate resource contention or delays processing API server requests.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{namespace=\"$SystemNamespace\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Queue Depth",
   "type": "stat",
   "description": "The number of reconcile requests that are waiting to be processed by the controller. A growing queue depth can indicate that the Kubernetes API Server or the controller does not have enough resources. This can lead to pods taking longer to be deleted or started. ",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum (workqueue_depth{namespace=\"$SystemNamespace\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "stat",
   "description": "The number of workers that are currently being used to process reconcile requests. Increasing this number can reduce the work queue duration, but each new worker adds a small amount of time due to context switching.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (controller) (controller_runtime_active_workers)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Calls",
   "type": "timeseries",
   "description": "The number of calls to the API server",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "sum by (method, code) (rate(rest_client_requests_total{namespace=\"$SystemNamespace\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "description": "The time required by Prometheus to read and process metrics. Long scrape times can delay metrics updates or lead to metrics loss. Increasing time often indicates issues with metrics cardinality or cluster resources.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  }
 ]
}